---
title: "results"
author: "Nick Hagar"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drake)
```

## Story count changes (overall)
```{r}
loadd(data_noseason_stories)
loadd(rdd_model_data_noseason_stories)
plot(rdd_model_data_noseason_stories)
summary(rdd_model_data_noseason_stories)
```

## Byline count changes (overall)
```{r}
loadd(data_noseason_bylines)
loadd(rdd_model_data_noseason_bylines)
plot(rdd_model_data_noseason_bylines)
summary(rdd_model_data_noseason_bylines)
```

## Storyper count changes (cohort)
```{r}
loadd(cohort_agg_storiesper)
loadd(cohort_rdd_cohort_agg_storiesper)
#plot(cohort_rdd_cohort_agg_storiesper)
summary(cohort_rdd_cohort_agg_storiesper)
```

## Tweet embed changes (cohort)
```{r}
loadd(cohort_agg_pct_tweet)
loadd(cohort_rdd_cohort_agg_pct_tweet)
#plot(cohort_rdd_cohort_agg_pct_tweet)
summary(cohort_rdd_cohort_agg_pct_tweet)
```

## Polarity changes (cohort)
```{r}
loadd(cohort_agg_polarity)
loadd(cohort_rdd_cohort_agg_polarity)
#plot(cohort_rdd_cohort_agg_polarity)
summary(cohort_rdd_cohort_agg_polarity)
```

## Insta embed changes (cohort)
```{r}
loadd(cohort_agg_pct_insta)
loadd(cohort_rdd_cohort_agg_pct_insta)
#plot(cohort_rdd_cohort_agg_pct_insta)
summary(cohort_rdd_cohort_agg_pct_insta)
```

## Char count changes (cohort)
```{r}
loadd(cohort_agg_log_len_chars)
loadd(cohort_rdd_cohort_agg_log_len_chars)
#plot(cohort_rdd_cohort_agg_log_len_chars)
summary(cohort_rdd_cohort_agg_log_len_chars)
```

## Word count changes (cohort)
```{r}
loadd(cohort_agg_log_len_words)
loadd(cohort_rdd_cohort_agg_log_len_words)
#plot(cohort_rdd_cohort_agg_log_len_words)
summary(cohort_rdd_cohort_agg_log_len_words)
```

## Section composition
```{r}
readd(plot_sections)
```

