---
title: "Time series analysis"
author: "Nick Hagar"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source('../scripts/functions_ts.R')
source('../scripts/functions_metadata.R')
source('../scripts/functions_text.R')
```


## Loading and aggregating data
```{r loaddata}
df <- load_data()

df_agg <- agg_df(df, '2019-01-05', '2019-02-07')

ts_weekly <- convert_ts(df_agg)
```

## Text features
```{r textprocessing}
df <- df %>% 
  #Count social embeds
  text_embeds(.) %>% 
  #Remove social embeds
  mutate(text_body=text_clean(text_body)) %>% 
  #Calculate length
  text_lengths(.) %>% 
  #Tag with sentiment
  text_sent(.)

#TODO: Tag NLP
df

#Transform measures
df <- df %>% 
  select(-text_body, -hed, -subhed) %>% 
  mutate(neg_pct=negative/len_words,
         pos_pct=positive/len_words,
         log_len_chars=log1p(len_chars),
         log_len_words=log1p(len_words),
         has_tweet=tweets>0,
         has_insta=insta>0)

#Aggregate all measures to the daily level
df %>% 
  group_by(pub_date) %>% 
  summarize(stories=n(), bylines=n_distinct(byline),
            log_len_chars=mean(log_len_chars), log_len_words=mean(log_len_words),
            neg_pct=mean(neg_pct), pos_pct=mean(pos_pct),
            pct_tweet=sum(has_tweet)/n(),
            pct_insta=sum(has_insta)/n()) %>% 
  mutate(day_of_week=wday(pub_date))
```


## Aggregate time series analysis
```{r decomposition}
decomp_plots(ts_weekly)
```

```{r}
decomposed <- decompose(ts_weekly)

deseasoned <- decomposed$x - decomposed$seasonal
plot(deseasoned)

df_agg$deseasoned <- deseasoned
```


```{r modeling}
model <- lm_df(df_meta_agg, '2019-01-25')
summary(model)
```

```{r detrend}
detrend_ts(ts_weekly)
```

## Regression discontinuity analysis
```{r}
library(rdrobust)
library(rdd)

df_agg <- df_agg %>% 
  ungroup() %>% 
  mutate(relative_days=as.integer(pub_date-as_date("2019-01-25"))) %>% 
  filter(relative_days>=-12)

rdrobust(df_agg$stories, df_agg$relative_days, covs = df_agg$day_of_week)

est <- RDestimate(deseasoned ~ relative_days, data=df_agg, cutpoint = 0)

est_cov <- RDestimate(stories ~ relative_days | day_of_week, data=df_agg, cutpoint = 0)

summary(est)

plot(est_cov)

df_agg %>% 
  RDestimate(stories ~ relative_days)

df_agg
```

